### ISSUE TITLE
Mydumper 报错 “Segmentation fault” 怎么解决？

### ISSUE THREAD

**Issue by wonderful1984** [pingcap/mydumper#32]
1、从这里看要升级到最新版本
https://pingcap.com/docs-cn/v3.0/reference/tools/mydumper/

2、已经是最新
 bin]$ ./mydumper -V
mydumper 0.9.5 (d3e6fec8b069daee772d0dbaa47579f67a5947e7), built against MySQL 5.7.24

运行中还是报 Segmentation fault

./mydumper --user=aaaa --password=aaaa -S /tmp/mysql10080.sock --database=user_db --no-locks --outputdir=/mysql_backup/user_db -v 1  --chunk-filesize=250 --skip-tz-utc --logfile=/mysql_backup/dumper_user_db.log -t 16 -N 

<pre>
Segmentation fault (core dumped)
</pre>

OS kernel: 3.10.0-862.9.1.el7.x86_64 (Centos 7)

**Comment by wonderful1984** [comment]
<pre>
mmap(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x2b012140a000
mprotect(0x2b012140a000, 4096, PROT_NONE) = 0
clone(child_stack=0x2b0121609e30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b012160a9d0, tls=0x2b012160a700, child_tidptr=0x2b012160a9d0) = 40194
futex(0xc59bd8, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xff2a50, FUTEX_WAIT_PRIVATE, 12, NULL) = 0
mmap(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x2b012160b000
mprotect(0x2b012160b000, 4096, PROT_NONE) = 0
clone(child_stack=0x2b012180ae30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b012180b9d0, tls=0x2b012180b700, child_tidptr=0x2b012180b9d0) = 40315
futex(0xff2a50, FUTEX_WAIT_PRIVATE, 13, NULL) = 0
mmap(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x2b012180c000
mprotect(0x2b012180c000, 4096, PROT_NONE) = 0
clone(child_stack=0x2b0121a0be30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b0121a0c9d0, tls=0x2b0121a0c700, child_tidptr=0x2b0121a0c9d0) = 40388
futex(0xc59bd8, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xff2a50, FUTEX_WAIT_PRIVATE, 14, NULL) = 0
mmap(NULL, 2101248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x2b0121a0d000
mprotect(0x2b0121a0d000, 4096, PROT_NONE) = 0
clone(child_stack=0x2b0121c0ce30, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, parent_tidptr=0x2b0121c0d9d0, tls=0x2b0121c0d700, child_tidptr=0x2b0121c0d9d0) = 40515
futex(0xc59bd8, FUTEX_WAKE_PRIVATE, 1)  = 1
futex(0xff2a50, FUTEX_WAIT_PRIVATE, 15, NULL) = 0
sendto(4, "\21\0\0\0\2vipshop_archives", 21, 0, NULL, 0) = 21
recvfrom(4, "\7\0\0\1\0\0\0\3\0\0\0", 16384, 0, NULL, NULL) = 11
sendto(4, "\22\0\0\0\3SHOW TABLE STATUS", 22, 0, NULL, 0) = 22
recvfrom(4, "\1\0\0\1\22\36\0\0\2\3def\0\0\0\4Name\4Name\f.\0\210\0\0"..., 16384, 0, NULL, NULL) = 1448
recvfrom(4, "_order_header_20171128\6InnoDB\00210"..., 16384, 0, NULL, NULL) = 2642
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

</pre>

**Comment by wonderful1984** [comment]
tidb 的问题，已fix

**Comment by WangXiangUSTC** [comment]
could you please provide which problem of TiDB cause this error? @wonderful1984
