### ISSUE TITLE
Using mydumper backups is always failure

### ISSUE THREAD

**Issue by wonderful1984** [pingcap/mydumper#33]
Could not read data from db_name.table: stream response error: [9007]Execution terminated due to exceeding max time limit

从A机器，使用mydumper 备份tidb集群里的某个DB

<pre>
./mydumper --user=<USER> --password=<PWD> -h <IP> -P <PORT> --database=<DBNAME> --outputdir=/mysql_backup/<DBNAME> -v 2 --chunk-filesize=250 --skip-tz-utc --logfile=/mysql_backup/dumper_<DBNAME>.log -t 8 -N --complete-insert

版本
./mydumper -V
mydumper 0.9.5 (4cf0556b767b9a7086bf5fed213a4101b8439bbb), built against MySQL 5.7.24
</pre>

<pre>
+--------------------------------+----------+
| Variable_name                  | Value    |
+--------------------------------+----------+
| innodb_rollback_on_timeout     | 0        |
| interactive_timeout            | 28800    |
| innodb_flush_log_at_timeout    | 1        |
| connect_timeout                | 10       |
| slave_net_timeout              | 3600     |
| lock_wait_timeout              | 31536000 |
| net_read_timeout               | 30       |
| innodb_lock_wait_timeout       | 50       |
| rpl_semi_sync_master_timeout   |          |
| tidb_wait_split_region_timeout | 300      |
| wait_timeout                   | 28800    |
| net_write_timeout              | 60       |
| rpl_stop_slave_timeout         | 31536000 |
| delayed_insert_timeout         | 300      |
+--------------------------------+----------+

+-----------------------------------+--------+
| Variable_name                     | Value  |
+-----------------------------------+--------+
| rbr_exec_mode                     |        |
| executed_gtids_compression_period |        |
| slave_exec_mode                   | STRICT |
| gtid_executed_compression_period  |        |
| max_execution_time                | 0      |
+-----------------------------------+--------+
</pre>

**Comment by amyangfei** [comment]
1. Fave you checked whether there are some error logs in TiDB
2. If there are queries in PROCESSLIST running longer than 60s, mydumper will abort dump, try to use --long-query-guard to change the guard value. But seems don't match this scenario.

**Comment by wonderful1984** [comment]
Only backups, no other SQL

**Comment by wonderful1984** [comment]
我尝试修改了一下，timeout看看能否成功，目的：备份一个3T的db出来
<pre>
+--------------------------------+----------+
| Variable_name                  | Value    |
+--------------------------------+----------+
| innodb_rollback_on_timeout     | 0        |
| connect_timeout                | 10       |
| slave_net_timeout              | 3600     |
| lock_wait_timeout              | 31536000 |
| net_read_timeout               | 86400    | <----- changed
| innodb_lock_wait_timeout       | 50       |
| rpl_semi_sync_master_timeout   |          |
| tidb_wait_split_region_timeout | 300      |
| wait_timeout                   | 86400    | <----- changed
| net_write_timeout              | 86400    | <----- changed
| rpl_stop_slave_timeout         | 31536000 | 
| delayed_insert_timeout         | 300      |
| interactive_timeout            | 28800    |
| innodb_flush_log_at_timeout    | 1        |
+--------------------------------+----------+
</pre>

**Comment by wonderful1984** [comment]
还是一样的错误，无法完整整库备份出来……

**Comment by amyangfei** [comment]
Could you please paste the error log in tidb

**Comment by wonderful1984** [comment]
TiDB我开启了stream，这个有无关系？
<pre>

[2019/09/27 00:17:43.140 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801042:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2019/09/27 00:17:43.140 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801042:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2019/09/27 00:17:43.140 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801042:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2019/09/27 00:17:43.140 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801042:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2019/09/27 00:17:43.140 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801042:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2019/09/27 00:17:43.140 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801042:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2019/09/27 00:17:45.085 +08:00] [WARN] [conn.go:669] ["command dispatched failed"] [conn=6] [connInfo="id:6, addr:mydumper_IP:12329 status:3, collation:latin1_swedish_ci, user:importdata"] [command=Query
] [sql="SELECT /*!40001  SQL_NO_CACHE */ * FROM `user_database`.`user_table`  "] [err="stream response error: [9007]Execution terminated due to exceeding max time limit\n\ngithub.com/pingcap/tidb/distsql.(*streamResult).readDataFromResponse\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/distsql/stream.go:89\ngithub.com/pingcap/tidb/distsql.(*streamResult).readDataIfNecessary\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/distsql/stream.go:112\ngithub.com/pingcap/tidb/distsql.(*streamResult).Next\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/distsql/stream.go:53\ngithub.com/pingcap/tidb/executor.(*tableResultHandler).nextChunk\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/table_reader.go:235\ngithub.com/pingcap/tidb/executor.(*TableReaderExecutor).Next\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/table_reader.go:155\ngithub.com/pingcap/tidb/executor.Next\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/executor.go:202\ngithub.com/pingcap/tidb/executor.(*recordSet).Next\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:156\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:365\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1340\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1306\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1223\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:899\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:653\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:438\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"]
[2019/09/27 00:17:45.087 +08:00] [INFO] [server.go:414] ["connection closed"] [conn=6]
[2019/09/27 00:17:49.143 +08:00] [INFO] [client_batch.go:536] ["recycle idle connection"] [target=store 801041:20160]
[2019/09/27 00:17:49.144 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801041:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
[2019/09/27 00:17:49.144 +08:00] [ERROR] [client_batch.go:286] ["batchRecvLoop error when receive"] [target=store 801041:20160] [error="rpc error: code = Canceled desc = grpc: the client connection is closing"]
</pre>

**Comment by wonderful1984** [comment]
如果不开stream……直接OOM，我要导出3TB的数据

<pre>
[9759299.192213] Out of memory: Kill process 8039 (tidb-server) score 915 or sacrifice child
[9759299.192233] Killed process 8039 (tidb-server) total-vm:120389404kB, anon-rss:60421632kB, file-rss:0kB, shmem-rss:0kB

</pre>

**Comment by amyangfei** [comment]
what's the version of TiDB, some version has known OOM issue.

**Comment by amyangfei** [comment]
Try to use the -r option, which will benefit with single table concurrent and decrease memory consume. The `-r value` could be `256MB / average-row-size.`

**Comment by wonderful1984** [comment]
<pre>
Release Version: v4.0.0-alpha-303-gf792e8d78-dirty
Git Commit Hash: f792e8d7879c13c5ee250c6242269527303369a2
Git Branch: master
UTC Build Time: 2019-09-19 11:41:53
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
</pre>

**Comment by wonderful1984** [comment]
<pre>
[apps@localhost mysql_backup]$ ps -ef|grep tidb
apps     134788      1 19 11:27 pts/0    00:03:30 ./tidb-server --config /apps/conf/tidb/tidb10080.toml
apps     148225 166550 33 11:44 pts/3    00:00:08 ./mydumper --user=--password=-h  -P --no-locks --database= --outputdir=/mysql_backup/tidb_data -v 2 -r 1000000 --skip-tz-utc --logfile=/mysql_backup/dumper.log -t 8 -N --complete-insert

[apps@localhost mysql_backup]$ pidstat -r -p 134788 5
Linux 3.10.0-862.9.1.el7.x86_64 (localhost)        09/27/2019      _x86_64_        (40 CPU)

11:45:05 AM   UID       PID  minflt/s  majflt/s     VSZ    RSS   %MEM  Command
11:45:10 AM   500    134788 455862.00      0.00 43927296 39267512  60.06  tidb-server
11:45:15 AM   500    134788 269545.00      0.00 45531612 40745364  62.32  tidb-server
11:45:20 AM   500    134788 228678.00      0.00 47479948 42702220  65.32  tidb-server
11:45:25 AM   500    134788 323547.00      0.00 52003540 47216856  72.22  tidb-server
11:45:30 AM   500    134788 291852.00      2.80 55776688 50949784  77.93  tidb-server
11:45:35 AM   500    134788 261689.80    171.40 59137460 53619420  82.02  tidb-server
</pre>
